name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install SBCL
        run: |
          make setup/sbcl

      - name: Build
        run: |
          make build

      - name: Unit Tests
        run: |
          make test/unit
